[package]
name = "USDH"

[dependencies]
#One = { git = "https://github.com/one-chain-labs/onechain.git", subdir = "crates/sui-framework/packages/one-framework", rev = "main" }

[addresses]
usdh = "0x0"
sui = "0x2"
std = "0x1"